### ISSUE TITLE
When you get close

### ISSUE THREAD

**Issue by mrquincle** [crownstone/CrownstoneApp#12]
Hardware: Android

First I thought this functionality didn't work at all. However, after I restarted the app it did work at least once that when I got closer it turned on after a while. Regretfully it doesn't turn off when I leave. I tried to configure the range to have it turn off as far as possible from it. 

Perhaps it finds it hard to distinguish between me being very far and not being visible at all? Or is there a bug in the Android version?

I also can't see how good the Crownstone can see me.

**Comment by AlexDM0** [comment]
The define range (as you reported) is currently broken on android. The default range may be a bit far away. We will test this in more detail.

Thanks for reporting!

**Comment by AlexDM0** [comment]
#9 is about the same, lets continue there.
