### ISSUE TITLE
statusbar

### ISSUE THREAD

**Issue by vliedel** [crownstone/CrownstoneApp#14]
> 12-26 12:28:56.169 30611-32164/rocks.crownstone.consumerapp W/ReactNativeJS: Possible Unhandled Promise Rejection (id: 0):
                                                                             Tried to change the status bar while not attached to an Activity
                                                                             createErrorFromErrorData@http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:7157:20
                                                                             http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:7120:59
                                                                             __invokeCallback@http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:7500:15
                                                                             http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:7352:24
                                                                             guard@http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:7271:3
                                                                             invokeCallbackAndReturnFlushedQueue@http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:7351:6
                                                                             invokeCallbackAndReturnFlushedQueue@[native code]

**Comment by AlexDM0** [comment]
You got a red screen on a release build? This seems to refer to your implementation of the status bar change.

**Comment by vliedel** [comment]
Nah, this was not a release build :) Maybe should've put it more into context.

**Comment by AlexDM0** [comment]
Lets leave the issues for release build bugs ;)
