### ISSUE TITLE
Configuring sensitivity of tap-to-toggle functionality

### ISSUE THREAD

**Issue by mrquincle** [crownstone/CrownstoneApp#18]
The tap-to-toggle functionality is very cool. However, it would be great to configure its sensitivity. Now at times I'm sitting >2 meters away and it's still shaking and subsequently switching.

**Comment by AlexDM0** [comment]
Could you measure the rssi with any other app?

**Comment by mrquincle** [comment]
Now I got this situation having my phone positioned firmly on a table at around one meter from a Crownstone. I understand that at times the signal strength due to some weird trick of nature might spuriously go beyond a certain level. Remedies for this:

- Take into account that the phone didn't move at all. Hence, tap-to-toggle functionality does not need to run.
- I suppose multiple consecutive values are averaged before the signal strength is compared with a threshold. Sensitivity can be seen as on an RSSI level, but also on a speed / latency level. Due to the variety of smartphone devices it might make sense to allow the user not only to set the tap-to-toggle range but also the sensitivity (technically the size of the sliding window).
- Tap-to-toggle has the connotation that there should be a "tap". A physical touch event can be registered by use of the accelerometer on the phone. This has as disadvantage that it would use the battery. It might also change the system from exhibiting spurious tap-to-toggle events (false positives) to being less robust in registering true events (false negatives).

The 2 meter away thing is easily reproduced, also @vliedel experiences this.

**Comment by vliedel** [comment]
Here's the RSSI values when i move it from 1m away from the crownstone plug to against it:
![screenshot_20170111-080949](https://cloud.githubusercontent.com/assets/2011969/21961767/520d0b1e-db13-11e6-8463-919ee9f50133.png)

And here is me sitting at 2m away from it:
![screenshot_20170111-075933](https://cloud.githubusercontent.com/assets/2011969/21961770/851f8e64-db13-11e6-94fc-28292cb2ffdc.png)

**Comment by mrquincle** [comment]
This can now be trained by the user.
