### ISSUE TITLE
Taking a picture on Android

### ISSUE THREAD

**Issue by mrquincle** [crownstone/CrownstoneApp#2]
Taking a picture on Android, Samsung S5, shows a black screen and after saying okay, use that, it halts at "Processing".

**Comment by AlexDM0** [comment]
Thanks for reporting! The android version is a bit rough around the edges at the moment but we'll try pushing updates very quickly. 

Well look into this tomorrow. 

Regards,

Alex

**Comment by mrquincle** [comment]
Although it doesn't have a screen anymore, it keeps "Processing" forever. Perhaps disabling the possibility to take a picture is a better user experience. Now the first experience is this and that I have to fill in my data twice!

**Comment by vliedel** [comment]
> { [Error: /storage/emulated/0/Pictures/IMG_20161226_125238.jpg: open failed: EACCES (Permission denied)] framesToPop: 1, code: 'EUNSPECIFIED' }

**Comment by AlexDM0** [comment]
This seems an issue with the storage location of the pictures. I'll look into paths for this. Thanks for reporting!

**Comment by AlexDM0** [comment]
We've looked into this and its a bit more complicated than expected. We've disabled the pictures on android for now and are working on a fix.

**Comment by mrquincle** [comment]
Half a year passed. This must be a tough one. What's so difficult about it?

**Comment by mrquincle** [comment]
It's being addressed in https://github.com/crownstone/CrownstoneApp/commit/a30c98fe4831fd41db7703be1d32e7d1af56f508
