### ISSUE TITLE
Crownstone app uses >35 MB of storage

### ISSUE THREAD

**Issue by mrquincle** [crownstone/CrownstoneApp#20]
The Crownstone app (version 0.7.5) uses >35 MB of storage. It's recommendable to reduce the size:

- Reduced size leads to fewer deinstalls for guest-use of the Crownstone app.
- Reduced size leads to higher performance.
- Reduced size is required for older smartphones 
- Reduced size means faster downloads of the app.

It is possible for example to only distribute the apk's for a particular native platform: https://realm.io/news/reducing-apk-size-native-libraries called APK splits. However, note that a basic React app should be around 3 MB. It's likely that around 30 MB is used for graphics that isn't optimized.

**Comment by mrquincle** [comment]
What has been done to restrict size?

**Comment by AlexDM0** [comment]
Nothing. Non issue.

**Comment by mrquincle** [comment]
It's okay to `wontfix` something, but to suggest that an issue reported is a non issue is a bit rude.

From the article:

**Why You Should Care About APK Size**

> A couple of megabytes saved might not look much to owners of modern devices, but there is a vast number of older or low-end devices out there in Androidland that don’t have the luxury of free storage space. In fact, as Android is especially popular in emerging economies, most devices running Android apps do not look like your iPhones or Nexuses — some only have a few dozen megabytes of space available for all apps, meaning that installing an app of a few megs will usually necessitate deleting another app. Often, a high megabyte size will be the difference between getting an install or not, for those space-strapped users.

See also https://developer.android.com/topic/performance/reduce-apk-size.html, where Google has especially addressed this non issue.

See also https://cyrilmottier.com/2014/08/26/putting-your-apks-on-diet/ 

> Publishing light-weight applications on the Play Store is a good practice every developer should focus on when designing an application. Why? First, because it is synonymous with a simple, maintainable and future-proof code base. Secondly, because developers would generally prefer staying below the Play Store current 50MB APK limit rather than dealing with download extensions files. Finally because we live in a world of constraints: limited bandwidth, limited disk space, etc. The smaller the APK, the faster the download, the faster the installation, the lesser the frustration and, most importantly, the better the ratings.

Here you have the top 12 reasons of deinstalling an app: https://www.linkedin.com/pulse/top-12-reasons-why-users-frequently-uninstall-mobile-apps-fakhruddin. Guess what's on number 1.

You'll be finding a lot of app developers addressing this non issue:

- https://medium.com/pregbuddy-engineering/how-we-reduced-our-android-app-size-by-65-54b17ae9a3c6
