### ISSUE TITLE
Unable to set "home name" on first run

### ISSUE THREAD

**Issue by nallath** [crownstone/CrownstoneApp#23]
OS; Android CyanogenMod 13.1.2
Phone: OneplusOne

When running the "first run wizard", the application asks you to enter the name & gender of your home. Regardless of the gender & data entered in the name field, I always received a "I would like a name" message. I'm not a 100% sure about it, but i think it might have something to do with first changing the gender (I can't re-test it). 

The only option left was to skip this test. It is possible to set the name after the first run.

**Comment by AlexDM0** [comment]
Hi Jaime,

Sorry for the bad starting experience. Thanks for notifying! I'll try to reproduce and fix this for our upcoming next release. Hopefully it will be out next week!

Regards,

Alex

**Comment by nallath** [comment]
No worries. It's minor issue at best.

**Comment by AlexDM0** [comment]
This has been fixed in the upcoming release. Thanks for letting us know!
