### ISSUE TITLE
App version

### ISSUE THREAD

**Issue by mrquincle** [crownstone/CrownstoneApp#30]
It would be great to be able to see somewhere the app version without the need to:

1. log out
2. go to the app store

Can be in an about window for example.

**Comment by AlexDM0** [comment]
iOS has this in the settings window. We'll see if we can put it somewhere
in Andoid as well.

**Comment by mrquincle** [comment]
It is very useful. People can also be in beta for example or perhaps due to a failing internet connection have an older version of the app than listed on the store.

**Comment by AlexDM0** [comment]
Added
