### ISSUE TITLE
App clears login credetials

### ISSUE THREAD

**Issue by ArthurvdMolen** [crownstone/CrownstoneApp#32]
In situations where the crownstones can not be reached (other location) and/or bluetooth is not available the APP drops the credentials which is annoying,

**Comment by AlexDM0** [comment]
Hi Arthur,

Is this roughly about once a week? I'll see if I can get this fixed for our next release. Thanks for letting us know!

Cheers

**Comment by AlexDM0** [comment]
This has been fixed in version 1.9.1. which was released yesterday.
