### ISSUE TITLE
Hint to buy Crownstones on getting the app

### ISSUE THREAD

**Issue by mrquincle** [crownstone/CrownstoneApp#33]
### Expected

A way / direction to get the actual hardware required to be used with the app. For example at one of the first screens.

### Actual 

No hints at all.

### Steps to reproduce

1. Install app
2. Look at screen.

### Configuration

- App version: 1.11.2.26

### Checks

Make sure the following boxes are checked before submitting the issue - thanks!

- [x] Check that you can login through <https://cloud.crownstone.rocks/>

**Comment by AlexDM0** [comment]
This has been added to the app
