### ISSUE TITLE
What is a good name for my home AI?

### ISSUE THREAD

**Issue by mrquincle** [crownstone/CrownstoneApp#4]
It would be great to have some inspiration to name my AI.

This [article](https://www.scientificamerican.com/article/smart-home-city-ambient-intelligence/) mentions the Jetsons, but even that brainy home didn't have a name... Alexa has its own name that you can't choose, although it also listens to Amazon.

Zuckerburg calls his home AI [Jarvis](https://www.cnet.com/news/zuckerberg-shows-off-jarvis-his-smart-home-ai/), the AI that Stark uses to control his home in Iron Man.

A list of inspiring options would be nice!

**Comment by AlexDM0** [comment]
The default name rosii is inspired by the jetsons. If you can come up with a few nice names we'd be happy to add them in random pick button :)

**Comment by AlexDM0** [comment]
Added in 1.9.1.1:

Current selection:

{name:'Amy', gender:'female'},
      {name:'Anne', gender:'female'},
      {name:'Bob', gender:'male'},
      {name:'Clive', gender:'male'},
      {name:'Crowny', gender:'female'},
      {name:'Daisy', gender:'female'},
      {name:'Dobby', gender:'male'},
      {name:'Dotty', gender:'female'},
      {name:'Grey', gender:'male'},
      {name:'Evy', gender:'female'},
      {name:'Eve', gender:'female'},
      {name:'HAL', gender:'male'},
      {name:'James', gender:'male'},
      {name:'Marvin', gender:'male'},
      {name:'Nikki', gender:'female'},
      {name:'Pulli', gender:'female'},
      {name:'Robby', gender:'male'},
      {name:'Sam', gender:'female'},
      {name:'Sam', gender:'male'},
      {name:'Sky', gender:'female'},
      {name:'Suzy', gender:'female'},
      {name:'Rosii', gender:'female'},
      {name:'Sonny', gender:'male'},
      {name:'Stanley', gender:'male'},
      {name:'Tron', gender:'male'},
      {name:'Wally', gender:'male'},
      {name:'Watson', gender:'male'},
