### ISSUE TITLE
No Crownstones Added

### ISSUE THREAD

**Issue by mrquincle** [crownstone/CrownstoneApp#5]
I see this screen of "No Crownstones Added" and it says to go to settings, but where can I find these settings? Swiping doesn't work.

Hardware: Android 5, Samsung S5.

**Comment by AlexDM0** [comment]
I'm going to assume this is about the android version. 

This is a bug. The hamburger menu is hidden here accidentally. The iOS version has a different menu structure and the android version is quickly catching up. This specific one has slipped through I'm afraid. Well likely release a hot fix tomorrow. 

Keep in mind though, the description is aimed at silent or previously owned Crownstones which could be recovered. If you're just trying out your new Crownstones, all you have to do is stand close to it and it will pop up, waiting for you to click it!

Cheers

**Comment by vliedel** [comment]
Fixed with https://github.com/crownstone/CrownstoneApp/commit/10412f9fb8854e4379baecc424e226114beb3ca2
